### PR TITLE
Compatibility with Storybook 3, dependency updates

### PR DESCRIPTION
**Pull request by benbender**

### CODE REVIEW

**Comment by faceyspacey** [comment]
Hey there, I haven't had the time for this stuff as I'd hoped. I'm gonna merge your commit and add you as a maintainer as you seem to understand it all. Great work!

**Comment by benbender** [comment]
Hey, thank you :) But tbh I digged around in the code for an hour or so and made it work for me. It's working, but the real problem is storybook-addon-specifications. Storybook 3 supports a hierarchy of stories with "/" as separator. That's not really supported by the specifications addon atm so you get into trouble if you try to see your tests under your story. I'll try to find time to have a look when I'm done with my actual project.

**Comment by faceyspacey** [comment]
ok. i just published what you did. better something working, than not.

...in the future, to be honest, when i do get to this, im gonna remake this functionality without storybook. i dont need all the storybook stuff. i just need my webpack bundle to rebuild with a different entry point, and i think i can do it in a fraction of the code.

**Comment by benbender** [comment]
Sry, but I don't get it - what functionality do you refer to? Snapshotting is done by jest, the storybook-ui by storybook. If you discard storybook, you'll get.. jest? :)

**Comment by faceyspacey** [comment]
im gonna make a tool that adds a menu to my app that lets me select tests that return "stories." then when u select a story from this menu, webpack rebuilds using the given story module as the entry point. 

im rebuilding the storybook entrypoint switching mechanism to use a lower level abstraction. i've recently done some work on Webpack itself that has been [merged](https://medium.com/faceyspacey/announcing-react-universal-component-2-0-babel-plugin-universal-import-5702d59ec1f4). I'm gonna modify webpack itself if I have to. It just should be easy as hell in userland to tell webpack to rebuild with a different entry point, in realtime, i.e. similar to HMR. 

Once that is done, the key feature of Storybook, which is just switching between entry points, becomes easy for anyone to do in userland.

Then from there, i'll build the connection to the jest tests.

**Comment by faceyspacey** [comment]
but in the end it will be a testing-*first* version of the core capability here.

**Pull request merged**
